POST http://127.0.0.1:3000/api/v1/users HTTP/1.1
Content-Type: application/json

{
   "name": "Nicolly Reis",
    "email": "nicolly654@email.com",
    "nameUser": "NicollyReis",
    "senha":"123456789"
}

###
POST http://127.0.0.1:3000/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
    "nameUser": "NicollyReis",
    "senha":"123456789"
}

###
GET http://127.0.0.1:3000/api/v1/users HTTP/1.1

###
GET http://127.0.0.1:3000/api/v1/users HTTP/1.1
###

###
PUT http://127.0.0.1:3000/api/v1/users/f5e58de2-23fa-4e7f-8023-ee73d4d1a26a HTTP/1.1
Content-Type: application/json

{
    "name": "Nicolly Souza",
    "email": "souza@email.com",
    "nameUser": "NicollySouza",
    "senha":"123456789"
}

##
DELETE http://127.0.0.1:3000/api/v1/1 HTTP/1.1


#eventos

###
POST http://127.0.0.1:3000/api/v1/events HTTP/1.1
Content-Type: application/json

{
    "description": "Levar o telefone na assistência técnica para arrumar",
    "date": "18/04/2025"
}

GET http://127.0.0.1:3000/api/v1/events HTTP/1.1

###
GET http://127.0.0.1:3000/api/v1/events/1 HTTP/1.1
###

###
PUT http://127.0.0.1:3000/api/v1/events/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Arrumar o celular",
    "description": "Levar o telefone na assistência técnica para arrumar",
    "date": "18/04/2025"
}