POST http://127.0.0.1:3000/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "Nicolly Reis",
    "email": "nicollyreis@email.com",
    "nome-Usuario": "NicollyReis",
    "senha":"123456789",
}

###
POST http://127.0.0.1:3000/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
    "nome-Usuario": "NicollyReis",
    "senha":"123456789",
}

###
GET http://127.0.0.1:3000/api/v1/users HTTP/1.1

###
GET http://127.0.0.1:3000/api/v1/users/1 HTTP/1.1
###